### ISSUE TITLE
Debian 11: Installation

### ISSUE THREAD

**Issue by Ramel** [updatengine-ng/updatengine-server#13]
In a Debian 11, the "install.sh" script doesn't run at first, then I have some strange errors with python venv command.

So I've run first:
```
# dos2unix -k -o install.sh
```
and
```
# dos2unix -k -o custom/.env
```

The python venv error is after running install script is:
```
[…]
Processing /tmp/tmpszxthznj/pkg_resources-0.0.0-py2.py3-none-any.whl
/bin/pip", line 2/ue
    /bin/python3
    ^
SyntaxError: invalid syntax
/bin/pip", line 2/ue
    /bin/python3
    ^
SyntaxError: invalid syntax
Create database updatengine
[…]
```
It not create a correct encode named ue venv folder:
```
# ls /srv/venv/
'ue'$'\r'
```

**Comment by noelmartinon** [comment]
Really strange to have had to use the command "dos2unix" because all the files already use the unix LF newline type in the repository.
Your venv directory was created with bad encoding script (or .env?). Just delete it and run again install.sh. You can check the install.sh (also .env file) encoding type with the command 'cat -A install.sh' and if you see only '$' at the end of the lines then its unix LF. Otherwise, for a Windows file, each line ended with '^M$' .

Another user encountered the same problem a while ago and I may have the cause there. Do you edit .env under Windows ? This could be the origin of the problem. In this case, I will have to modify the script to prevent this bug from occurring.

And thanks to have contribute with your pull request #12 !

**Comment by Ramel** [comment]
You're right I forgot to mention that it's a WSL Debian, and I've cloned the repo on the Windows side, then copied the install.sh to the WSL Debian user home . So I suppose the clone on Windows side convert the line-ending?

**Comment by noelmartinon** [comment]
The commit 6b2236f solved the issue
